version: '3.4'
volumes:
  db-data: {}
services:
  zupteste.api:
    image: ${DOCKER_REGISTRY-}zuptesteapi
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDev
      ASPNETCORE_URLS: http://+:5000;https://+:5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: DEVCERTPASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: src/ZupTeste.API/Dockerfile
    depends_on:
      - database
    ports:
      - '5000:5000'
      - '5001:5001'
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
